### ISSUE TITLE
Why is this set to output on stderr?

### ISSUE THREAD

**Issue by piersdb** [HPCE/hpce-2018-cw2#73]
Considering the CSV headers are necessary for nice CSV parsing, is there any reason why this output is cerr (stderr) rather than cout (stdout)?

https://github.com/HPCE/hpce-2018-cw2/blob/388dbafd20735d91e89bceb970aed4824fc9f904/src/time_fourier_transform.cpp#L94

**Comment by jjd06** [comment]
I don't think so... probably just a bug that's gone unnoticed for years. Fixed -- thanks!
