### ISSUE TITLE
Unable to push to private repo

### ISSUE THREAD

**Issue by moh1ka** [HPCE/hpce-2018-cw2#74]
Hi, i've followed your instructions on https://github.com/HPCE/hpce-2018-cw2/blob/master/git.md. However, after  `git push -u private master` I get the following error:
To https://github.com/HPCE/hpce-2018-cw2-mg5215.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/HPCE/hpce-2018-cw2-mg5215.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

When I try `git pull private master` I get the following error message:
From https://github.com/HPCE/hpce-2018-cw2-mg5215
 * branch            master     -> FETCH_HEAD
fatal: refusing to merge unrelated histories

When I do `git remote -v` I get:
origin	https://github.com/HPCE/hpce-2018-cw2 (fetch)
origin	https://github.com/HPCE/hpce-2018-cw2 (push)
private	https://github.com/HPCE/hpce-2018-cw2-mg5215.git (fetch)
private	https://github.com/HPCE/hpce-2018-cw2-mg5215.git (push)

Which is correct from what I understand...

**Comment by piersdb** [comment]
You have to do `git pull private master --allow-unrelated-histories` I think.

**Comment by jjd06** [comment]
That should do the trick. I think this wouldn't have been necessary had I not started adding to empty repos....

**Comment by moh1ka** [comment]
Thanks! I managed to make it work when I used `git pull --allow-unrelated-histories private master`. I was trying `git pull --allow-unrelated-histories` before posting the issue and receiving an "already up to date" message. Why is this the case?

**Comment by piersdb** [comment]
Probs because your current local branch is set to pull from origin remote rather than the private remote. As you cloned from origin, your local repo is up to date. You can change this behaviour when pushing to `private master` and using the -u flag.

**Comment by moh1ka** [comment]
Thanks!
