### ISSUE TITLE
Cant't push to private repo

### ISSUE THREAD

**Issue by Shuruili** [HPCE/hpce-2018-cw2#81]
When I tried to push to my private repo following the instructions I get this error message after I git push -u private master 
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Any suggestions?

**Comment by Db2515** [comment]
Did you manage to solve this?
I am having the same issue as well and am running out of ideas

**Comment by Shuruili** [comment]
Yes, you need to switch your private repo url from ssh to http. Check with this link: https://help.github.com/articles/changing-a-remote-s-url/  Then it should be able to push.

________________________________
发件人: Daniel Boulby <notifications@github.com>
发送时间: Monday, February 4, 2019 2:29:11 PM
收件人: HPCE/hpce-2018-cw2
抄送: Li, Shurui; State change
主题: Re: [HPCE/hpce-2018-cw2] Cant't push to private repo (#81)


Did you manage to solve this?
I am having the same issue as well and am running out of ideas

―
